name: Portfolio Deploy 
on:
  push:
    branches:
      - "main"
    paths:
      - "react-todo-list-app/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install
        run: npm ci
        working-directory: ./react-todo-list-app
      - name: Build
        run: npm run build
        working-directory: ./react-todo-list-app
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: todo-list-react
          folder: react-todo-list-app/build